FROM python:3.11-slim

WORKDIR /app
COPY ./app /app
COPY ./uploads /app/uploads
COPY ./email_automation.db /app/
COPY ./requirements.txt /app/
RUN pip install -r requirements.txt

EXPOSE 5000
CMD ["python", "app.py"]
